<?php

namespace Database\Seeders;

use App\Models\Business;
use App\Models\Event;
use App\Models\EventTag;
use App\Models\Place;
use App\Models\Province;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds for Events & Cultural Festivals in Cambodia.
     */
    public function run(): void
    {
        $pPhnomPenh  = Province::where('name', 'Phnom Penh')->first();
        $pSiemReap   = Province::where('name', 'Siem Reap')->first();
        $pBattambang = Province::where('name', 'Battambang')->first();
        $pSihanouk   = Province::where('name', 'Preah Sihanouk')->first();
        $pKampot     = Province::where('name', 'Kampot')->first();
        $pKep        = Province::where('name', 'Kep')->first();
        $pMondulkiri = Province::where('name', 'Mondulkiri')->first();
        $pKandal     = Province::where('name', 'Kandal')->first();

        $placeAngkorWat   = Place::where('name', 'Angkor Wat')->first();
        $placeRoyalPalace = Place::where('name', 'Royal Palace & Silver Pagoda')->first();
        $placeBokor       = Place::where('name', 'Bokor National Park')->first();
        $placeKepMarket   = Place::where('name', 'Kep Crab Market (Phsar Kdam)')->first();

        $bHeritage = Business::where('slug', 'angkor-heritage-restaurant-lounge')->first();
        $bMekong   = Business::where('slug', 'mekong-river-sunset-cruise-kayaking')->first();
        $bPhare    = Business::where('slug', 'phare-the-cambodian-circus')->first();

        $events = [
            [
                'title' => 'Bon Om Touk (Cambodian Water Festival)',
                'category' => 'Festival',
                'description' => 'Spectacular national holiday celebrating the reversing flow of the Tonle Sap River with 400+ vibrant dragon boats, illuminated floating barges (Loy Pratip), moon worship, and fireworks along the Phnom Penh riverfront.',
                'location' => 'Sisowath Quay Riverfront, Phnom Penh',
                'place_id' => $placeRoyalPalace?->id,
                'province_id' => $pPhnomPenh?->id,
                'business_id' => $bMekong?->id,
                'start_date' => '2026-11-15',
                'end_date' => '2026-11-17',
                'start_time' => '07:30 AM',
                'attendees_count' => 1800000,
                'price' => 'Free',
                'organizer' => 'National Committee for Organizing National and International Festivals',
                'featured' => true,
                'rating' => 4.95,
                'image_url' => 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Upcoming',
                'tags' => ['WaterFestival', 'BoatRace', 'KhmerCulture', 'Fireworks', 'NationalCelebration'],
            ],
            [
                'title' => 'Angkor Wat International Half Marathon',
                'category' => 'Sports',
                'description' => 'World-renowned charity race winding past 1,000-year-old temples inside the Angkor World Heritage site. Attracts global runners supporting landmine victims and children\'s hospitals in Cambodia.',
                'location' => 'Angkor Wat West Entrance, Siem Reap',
                'place_id' => $placeAngkorWat?->id,
                'province_id' => $pSiemReap?->id,
                'business_id' => null,
                'start_date' => '2026-12-06',
                'end_date' => '2026-12-06',
                'start_time' => '05:30 AM',
                'attendees_count' => 14000,
                'price' => '$65 USD',
                'organizer' => 'National Olympic Committee of Cambodia & Ministry of Tourism',
                'featured' => true,
                'rating' => 4.90,
                'image_url' => 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Scheduled',
                'tags' => ['Marathon', 'AngkorWat', 'Charity', 'Running', 'WorldHeritage'],
            ],
            [
                'title' => 'Angkor Sankranta (Khmer New Year Mega Celebration)',
                'category' => 'Festival',
                'description' => 'Grand annual Cambodian New Year festival organized in front of Angkor Wat, featuring traditional folk games, Khmer martial arts exhibitions (Bokator), giant sticky rice cake displays, and traditional dance circles.',
                'location' => 'Angkor Archaeological Park, Siem Reap',
                'place_id' => $placeAngkorWat?->id,
                'province_id' => $pSiemReap?->id,
                'business_id' => $bHeritage?->id,
                'start_date' => '2027-04-13',
                'end_date' => '2027-04-16',
                'start_time' => '08:00 AM',
                'attendees_count' => 2200000,
                'price' => 'Free',
                'organizer' => 'Union of Youth Federations of Cambodia (UYFC)',
                'featured' => true,
                'rating' => 4.98,
                'image_url' => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Upcoming',
                'tags' => ['KhmerNewYear', 'AngkorSankranta', 'Bokator', 'TraditionalGames', 'CulturalHeritage'],
            ],
            [
                'title' => 'Pchum Ben (Ancestors\' Day Ceremonies)',
                'category' => 'Cultural',
                'description' => '15-day religious festival dedicated to honoring ancestors and deceased relatives. Devotees visit at least seven Buddhist pagodas offering food and throwing sesame rice balls (Bay Ben) at dawn.',
                'location' => 'Historic Pagodas across Siem Reap & Phnom Penh',
                'place_id' => $placeRoyalPalace?->id,
                'province_id' => $pPhnomPenh?->id,
                'business_id' => null,
                'start_date' => '2026-10-09',
                'end_date' => '2026-10-11',
                'start_time' => '05:00 AM',
                'attendees_count' => 950000,
                'price' => 'Free (Donations Welcome)',
                'organizer' => 'Ministry of Cults and Religion & National Pagoda Committee',
                'featured' => false,
                'rating' => 4.88,
                'image_url' => 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Upcoming',
                'tags' => ['PchumBen', 'Buddhism', 'Spiritual', 'Pagoda', 'AncestorsDay'],
            ],
            [
                'title' => 'Phare Circus Performing Arts Festival',
                'category' => 'Arts',
                'description' => 'Week-long celebration of contemporary circus, street acrobatics, physical theatre, and visual arts featuring troupes from Cambodia, France, and across ASEAN.',
                'location' => 'Phare Circus Grounds, Ring Road, Siem Reap',
                'place_id' => null,
                'province_id' => $pSiemReap?->id,
                'business_id' => $bPhare?->id,
                'start_date' => '2026-09-20',
                'end_date' => '2026-09-25',
                'start_time' => '06:30 PM',
                'attendees_count' => 12000,
                'price' => '$25 - $38 USD',
                'organizer' => 'Phare Ponleu Selpak Arts Association',
                'featured' => true,
                'rating' => 4.96,
                'image_url' => 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Ongoing',
                'tags' => ['Circus', 'PerformingArts', 'Phare', 'Acrobatics', 'LiveTheatre'],
            ],
            [
                'title' => '11th Annual Cambodia Sea Festival',
                'category' => 'Festival',
                'description' => 'Coastal festival celebrating Cambodia\'s membership in the Most Beautiful Bays in the World Club with international beach sports, seafood gastronomy, sailing regatta, and live pop concerts.',
                'location' => 'Ochheuteal Beach & Sokha Beachfront, Sihanoukville',
                'place_id' => null,
                'province_id' => $pSihanouk?->id,
                'business_id' => null,
                'start_date' => '2026-12-18',
                'end_date' => '2026-12-20',
                'start_time' => '09:00 AM',
                'attendees_count' => 350000,
                'price' => 'Free',
                'organizer' => 'Ministry of Tourism & Preah Sihanouk Provincial Administration',
                'featured' => true,
                'rating' => 4.82,
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Upcoming',
                'tags' => ['SeaFestival', 'Beach', 'Seafood', 'CoastalTourism', 'Regatta'],
            ],
            [
                'title' => '9th National River Festival',
                'category' => 'Festival',
                'description' => 'Promoting freshwater river eco-tourism, organic agricultural trade, traditional boxing (Kun Khmer), and floating fruit markets along the Sangker River.',
                'location' => 'Sangker Riverfront Promenade, Battambang',
                'place_id' => null,
                'province_id' => $pBattambang?->id,
                'business_id' => null,
                'start_date' => '2027-03-20',
                'end_date' => '2027-03-22',
                'start_time' => '08:00 AM',
                'attendees_count' => 280000,
                'price' => 'Free',
                'organizer' => 'Ministry of Tourism & Battambang Provincial Administration',
                'featured' => false,
                'rating' => 4.79,
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Scheduled',
                'tags' => ['RiverFestival', 'Battambang', 'KunKhmer', 'EcoTourism', 'SangkerRiver'],
            ],
            [
                'title' => 'Royal Ploughing Ceremony (Preah Reach Pithi Chrat Preah Nongkal)',
                'category' => 'Cultural',
                'description' => 'Ancient royal agricultural divination ritual marking the beginning of the rice planting season. Sacred royal oxen predict upcoming crops, weather, and harvest yields.',
                'location' => 'Veal Preah Men (In front of National Museum), Phnom Penh',
                'place_id' => $placeRoyalPalace?->id,
                'province_id' => $pPhnomPenh?->id,
                'business_id' => null,
                'start_date' => '2027-05-14',
                'end_date' => '2027-05-14',
                'start_time' => '07:30 AM',
                'attendees_count' => 45000,
                'price' => 'Free',
                'organizer' => 'Royal Palace Ministry of Cambodia',
                'featured' => false,
                'rating' => 4.85,
                'image_url' => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Scheduled',
                'tags' => ['RoyalCeremony', 'Agriculture', 'Divination', 'Tradition', 'PhnomPenh'],
            ],
            [
                'title' => 'Cambodia International Film Festival (CIFF 2027)',
                'category' => 'Arts',
                'description' => 'Largest international film festival in the Kingdom, screening 130+ feature films, documentaries, and animation shorts from 35 nations with panel discussions by international directors.',
                'location' => 'Chaktomuk Theatre & Bophana Center, Phnom Penh',
                'place_id' => null,
                'province_id' => $pPhnomPenh?->id,
                'business_id' => null,
                'start_date' => '2027-06-24',
                'end_date' => '2027-06-28',
                'start_time' => '10:00 AM',
                'attendees_count' => 35000,
                'price' => 'Free (Advance registration)',
                'organizer' => 'Cambodia Film Commission & Bophana Center',
                'featured' => false,
                'rating' => 4.87,
                'image_url' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Scheduled',
                'tags' => ['FilmFestival', 'Cinema', 'Arts', 'PhnomPenh', 'Culture'],
            ],
            [
                'title' => 'Mondulkiri Highland Coffee & Eco-Harvest Fest',
                'category' => 'Festival',
                'description' => 'Celebration of indigenous Bunong agro-forestry, shade-grown Arabica and Robusta coffee roasting, highland honey harvesting, and pine canopy trail runs.',
                'location' => 'Sen Monorom Pine Forest Park, Mondulkiri',
                'place_id' => null,
                'province_id' => $pMondulkiri?->id,
                'business_id' => null,
                'start_date' => '2027-01-15',
                'end_date' => '2027-01-17',
                'start_time' => '08:30 AM',
                'attendees_count' => 18000,
                'price' => 'Free Entry',
                'organizer' => 'Mondulkiri Eco-Tourism Association & Department of Agriculture',
                'featured' => false,
                'rating' => 4.90,
                'image_url' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Upcoming',
                'tags' => ['CoffeeFestival', 'Mondulkiri', 'Highlands', 'EcoTourism', 'Bunong'],
            ],
            [
                'title' => 'Kep Crab & Seafood Gastronomy Festival',
                'category' => 'Dining',
                'description' => 'Three days of seaside culinary masterclasses, live cooking cook-offs featuring Kep flower crab, Kampot pepper sauce pairings, and fresh coastal oyster shucking.',
                'location' => 'Kep Crab Market Waterfront Promenade, Kep',
                'place_id' => $placeKepMarket?->id,
                'province_id' => $pKep?->id,
                'business_id' => null,
                'start_date' => '2027-02-12',
                'end_date' => '2027-02-14',
                'start_time' => '11:00 AM',
                'attendees_count' => 42000,
                'price' => 'Free Entry (Food tastings from $3)',
                'organizer' => 'Cambodia Restaurant Association & Kep Provincial Tourism',
                'featured' => true,
                'rating' => 4.92,
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Upcoming',
                'tags' => ['Seafood', 'KepCrab', 'KampotPepper', 'FoodFestival', 'Gastronomy'],
            ],
            [
                'title' => 'Bokor Mountain Trail Ultra Marathon (70km & 42km)',
                'category' => 'Sports',
                'description' => 'Challenging trail ultra marathon ascending through Bokor rainforests, waterfall canyons, and mist-shrouded historic French colonial ruins at 1,000m altitude.',
                'location' => 'Preah Monivong Bokor National Park, Kampot',
                'place_id' => $placeBokor?->id,
                'province_id' => $pKampot?->id,
                'business_id' => null,
                'start_date' => '2027-01-24',
                'end_date' => '2027-01-24',
                'start_time' => '04:30 AM',
                'attendees_count' => 2500,
                'price' => '$75 - $110 USD',
                'organizer' => 'Cambodia Trail Series & Ministry of Environment',
                'featured' => false,
                'rating' => 4.81,
                'image_url' => 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Upcoming',
                'tags' => ['TrailRunning', 'BokorMountain', 'UltraMarathon', 'Adventure', 'Kampot'],
            ],
            [
                'title' => 'Meak Bochea Candlelight Procession',
                'category' => 'Cultural',
                'description' => 'Sacred Buddhist holiday commemorating the spontaneous assembly of 1,250 enlightened monks before Lord Buddha. Features a mesmerizing evening lantern and candlelight walk ascending Oudong Mountain.',
                'location' => 'Preah Sakyamuni Chedi, Oudong Mountain, Kandal',
                'place_id' => null,
                'province_id' => $pKandal?->id,
                'business_id' => null,
                'start_date' => '2027-02-21',
                'end_date' => '2027-02-21',
                'start_time' => '05:30 PM',
                'attendees_count' => 60000,
                'price' => 'Free',
                'organizer' => 'Oudong Holy Pagoda Council & Ministry of Cults',
                'featured' => false,
                'rating' => 4.93,
                'image_url' => 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Scheduled',
                'tags' => ['MeakBochea', 'Candlelight', 'Oudong', 'Buddhism', 'Spiritual'],
            ],
            [
                'title' => 'Angkor Photo Festival & Master Workshops',
                'category' => 'Arts',
                'description' => 'Asia\'s longest-running international photography festival. Featured open-air projections, emerging Asian photographer masterclasses, and street exhibitions along the Siem Reap River.',
                'location' => 'Siem Reap River Gardens, Krong Siem Reap',
                'place_id' => null,
                'province_id' => $pSiemReap?->id,
                'business_id' => null,
                'start_date' => '2026-01-08',
                'end_date' => '2026-01-14',
                'start_time' => '06:00 PM',
                'attendees_count' => 20000,
                'price' => 'Free',
                'organizer' => 'Angkor Photo Association',
                'featured' => false,
                'rating' => 4.84,
                'image_url' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Completed',
                'tags' => ['Photography', 'PhotoFestival', 'SiemReap', 'VisualArts', 'Exhibition'],
            ],
            [
                'title' => 'Sihanoukville Regatta & Beach Soundwave',
                'category' => 'Sports',
                'description' => 'Offshore windsurfing and catamaran sailing regatta combined with acoustic beach sunset sessions on Otres Beach.',
                'location' => 'Otres Beach Marina, Preah Sihanouk',
                'place_id' => null,
                'province_id' => $pSihanouk?->id,
                'business_id' => null,
                'start_date' => '2026-08-10',
                'end_date' => '2026-08-12',
                'start_time' => '10:00 AM',
                'attendees_count' => 0,
                'price' => 'Free',
                'organizer' => 'Coastal Watersports Federation',
                'featured' => false,
                'rating' => 0.00,
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
                'status' => 'Cancelled',
                'tags' => ['Sailing', 'Regatta', 'BeachSports'],
            ],
        ];

        foreach ($events as $eventData) {
            $tags = $eventData['tags'] ?? [];
            unset($eventData['tags']);

            $event = Event::updateOrCreate(
                ['title' => $eventData['title']],
                $eventData
            );

            foreach ($tags as $tag) {
                EventTag::firstOrCreate([
                    'event_id' => $event->id,
                    'tag_name' => $tag,
                ]);
            }
        }
    }
}
