<?php

namespace Database\Seeders;

use App\Models\Province;
use Illuminate\Database\Seeder;

class ProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds for all 25 Provinces/Capital of Cambodia.
     */
    public function run(): void
    {
        $provinces = [
            [
                'name' => 'Phnom Penh',
                'type' => 'Capital City',
                'population' => '2,281,951',
                'area' => '679 km²',
                'districts_count' => 14,
                'communes_count' => 105,
                'status' => 'Active',
                'icon' => 'Building',
                'description' => 'The bustling capital of Cambodia blending French colonial architecture, royal landmarks, Wat Phnom, and riverfront dining.',
                'rating' => 4.80,
            ],
            [
                'name' => 'Siem Reap',
                'type' => 'Province',
                'population' => '1,014,234',
                'area' => '10,299 km²',
                'districts_count' => 12,
                'communes_count' => 100,
                'status' => 'Active',
                'icon' => 'Landmark',
                'description' => 'Gateway to Angkor Wat, ancient world heritage temples, vibrant night markets, and Tonle Sap lake floating villages.',
                'rating' => 4.95,
            ],
            [
                'name' => 'Battambang',
                'type' => 'Province',
                'population' => '997,000',
                'area' => '11,702 km²',
                'districts_count' => 14,
                'communes_count' => 96,
                'status' => 'Active',
                'icon' => 'Palette',
                'description' => 'Cambodia\'s artistic and agricultural heartland, famous for the Bamboo Train, Phare Circus, Wat Banan, and Phnom Sampov bat caves.',
                'rating' => 4.60,
            ],
            [
                'name' => 'Preah Sihanouk',
                'type' => 'Province',
                'population' => '300,000',
                'area' => '2,536 km²',
                'districts_count' => 5,
                'communes_count' => 29,
                'status' => 'Active',
                'icon' => 'Waves',
                'description' => 'Cambodia\'s premier coastal hub featuring pristine tropical islands (Koh Rong, Koh Rong Sanloem) and white sand beaches.',
                'rating' => 4.65,
            ],
            [
                'name' => 'Kampot',
                'type' => 'Province',
                'population' => '627,884',
                'area' => '4,873 km²',
                'districts_count' => 8,
                'communes_count' => 93,
                'status' => 'Active',
                'icon' => 'Mountain',
                'description' => 'Charming riverside province renowned for organic GI Kampot Pepper, Bokor Mountain plateau, and French colonial heritage.',
                'rating' => 4.70,
            ],
            [
                'name' => 'Kep',
                'type' => 'Province',
                'population' => '41,798',
                'area' => '336 km²',
                'districts_count' => 2,
                'communes_count' => 5,
                'status' => 'Active',
                'icon' => 'Utensils',
                'description' => 'Peaceful coastal province famous for fresh blue crab market, national park trails, and sunset sea views.',
                'rating' => 4.55,
            ],
            [
                'name' => 'Banteay Meanchey',
                'type' => 'Province',
                'population' => '859,545',
                'area' => '6,679 km²',
                'districts_count' => 9,
                'communes_count' => 65,
                'status' => 'Active',
                'icon' => 'Landmark',
                'description' => 'Northwestern province bordering Thailand, famous for Banteay Chhmar temple ruins, Poipet border gateway, and rich agricultural plains.',
                'rating' => 4.50,
            ],
            [
                'name' => 'Kampong Cham',
                'type' => 'Province',
                'population' => '895,760',
                'area' => '4,549 km²',
                'districts_count' => 10,
                'communes_count' => 109,
                'status' => 'Active',
                'icon' => 'Building',
                'description' => 'Central Mekong province renowned for the historic Kizuna Bridge, French colonial architecture, rubber plantations, and Wat Nokor.',
                'rating' => 4.45,
            ],
            [
                'name' => 'Kampong Chhnang',
                'type' => 'Province',
                'population' => '525,944',
                'area' => '5,521 km²',
                'districts_count' => 8,
                'communes_count' => 66,
                'status' => 'Active',
                'icon' => 'Utensils',
                'description' => 'Famous for traditional terracotta pottery making, floating villages on the Tonle Sap Lake, and scenic river landscapes.',
                'rating' => 4.40,
            ],
            [
                'name' => 'Kampong Speu',
                'type' => 'Province',
                'population' => '872,219',
                'area' => '7,017 km²',
                'districts_count' => 8,
                'communes_count' => 87,
                'status' => 'Active',
                'icon' => 'Mountain',
                'description' => 'Home to Phnom Aural (Cambodia\'s highest peak), Kirirom National Park pine forests, and authentic Palm Sugar production.',
                'rating' => 4.55,
            ],
            [
                'name' => 'Kampong Thom',
                'type' => 'Province',
                'population' => '677,260',
                'area' => '13,814 km²',
                'districts_count' => 8,
                'communes_count' => 81,
                'status' => 'Active',
                'icon' => 'Landmark',
                'description' => 'Home to Sambor Prei Kuk, a UNESCO World Heritage pre-Angkorian temple complex nestled inside serene jungle woodlands.',
                'rating' => 4.65,
            ],
            [
                'name' => 'Kandal',
                'type' => 'Province',
                'population' => '1,195,597',
                'area' => '3,179 km²',
                'districts_count' => 11,
                'communes_count' => 127,
                'status' => 'Active',
                'icon' => 'MapPin',
                'description' => 'Encircling the capital Phnom Penh, known for Oudong Royal Mountain, Koh Dach silk weaving island, and vibrant artisan crafts.',
                'rating' => 4.50,
            ],
            [
                'name' => 'Koh Kong',
                'type' => 'Province',
                'population' => '123,618',
                'area' => '11,160 km²',
                'districts_count' => 7,
                'communes_count' => 29,
                'status' => 'Active',
                'icon' => 'Trees',
                'description' => 'Southwestern eco-tourism paradise with the Cardamom Mountains, dense rainforests, Tatai Waterfalls, and pristine mangrove sanctuaries.',
                'rating' => 4.75,
            ],
            [
                'name' => 'Kratie',
                'type' => 'Province',
                'population' => '372,703',
                'area' => '11,094 km²',
                'districts_count' => 6,
                'communes_count' => 47,
                'status' => 'Active',
                'icon' => 'Waves',
                'description' => 'Famous Mekong river town known as the primary habitat for endangered Irrawaddy freshwater dolphins at Kampi rapids.',
                'rating' => 4.70,
            ],
            [
                'name' => 'Mondulkiri',
                'type' => 'Province',
                'population' => '88,649',
                'area' => '14,288 km²',
                'districts_count' => 5,
                'communes_count' => 21,
                'status' => 'Active',
                'icon' => 'Trees',
                'description' => 'Eastern highland province known for rolling pine hills, indigenous Bunong culture, ethical elephant sanctuaries, and Bou Sra Waterfall.',
                'rating' => 4.80,
            ],
            [
                'name' => 'Oddar Meanchey',
                'type' => 'Province',
                'population' => '261,252',
                'area' => '6,158 km²',
                'districts_count' => 5,
                'communes_count' => 24,
                'status' => 'Active',
                'icon' => 'Shield',
                'description' => 'Northern border province along Dangrek Mountains with rich historical landmarks, forest reserves, and cultural heritage.',
                'rating' => 4.35,
            ],
            [
                'name' => 'Pailin',
                'type' => 'Province',
                'population' => '70,486',
                'area' => '803 km²',
                'districts_count' => 2,
                'communes_count' => 8,
                'status' => 'Active',
                'icon' => 'Sparkles',
                'description' => 'Picturesque province situated at the foot of the Cardamom Mountains, historically famous for gemstone mining and peacock dances.',
                'rating' => 4.40,
            ],
            [
                'name' => 'Preah Vihear',
                'type' => 'Province',
                'population' => '251,352',
                'area' => '13,788 km²',
                'districts_count' => 8,
                'communes_count' => 51,
                'status' => 'Active',
                'icon' => 'Landmark',
                'description' => 'Home to the spectacular UNESCO World Heritage Prasat Preah Vihear cliffside temple perched atop Dângrêk Mountains.',
                'rating' => 4.85,
            ],
            [
                'name' => 'Prey Veng',
                'type' => 'Province',
                'population' => '1,057,428',
                'area' => '4,883 km²',
                'districts_count' => 13,
                'communes_count' => 116,
                'status' => 'Active',
                'icon' => 'Compass',
                'description' => 'Densely populated agricultural province on the east bank of the Mekong River with serene wetland sanctuaries and ancient mounds.',
                'rating' => 4.35,
            ],
            [
                'name' => 'Pursat',
                'type' => 'Province',
                'population' => '497,759',
                'area' => '12,692 km²',
                'districts_count' => 6,
                'communes_count' => 49,
                'status' => 'Active',
                'icon' => 'Mountain',
                'description' => 'Stretches from Tonle Sap Lake floating village of Kampong Luong to the Cardamom Mountains, famous for marble carving.',
                'rating' => 4.50,
            ],
            [
                'name' => 'Ratanakiri',
                'type' => 'Province',
                'population' => '203,989',
                'area' => '10,782 km²',
                'districts_count' => 9,
                'communes_count' => 50,
                'status' => 'Active',
                'icon' => 'Sun',
                'description' => 'Remote northeastern eco-tourism haven famous for Yeak Laom volcanic crater lake, tribal villages, and majestic waterfalls.',
                'rating' => 4.80,
            ],
            [
                'name' => 'Stung Treng',
                'type' => 'Province',
                'population' => '159,565',
                'area' => '11,092 km²',
                'districts_count' => 6,
                'communes_count' => 34,
                'status' => 'Active',
                'icon' => 'Waves',
                'description' => 'Northeastern province where the Sekong River meets the Mekong, known for Ramsar eco-wetlands and river cruises.',
                'rating' => 4.50,
            ],
            [
                'name' => 'Svay Rieng',
                'type' => 'Province',
                'population' => '524,725',
                'area' => '2,966 km²',
                'districts_count' => 8,
                'communes_count' => 80,
                'status' => 'Active',
                'icon' => 'MapPin',
                'description' => 'Southeastern border province connecting Phnom Penh with Ho Chi Minh City, featuring Bavet international gateway.',
                'rating' => 4.30,
            ],
            [
                'name' => 'Takeo',
                'type' => 'Province',
                'population' => '899,485',
                'area' => '3,563 km²',
                'districts_count' => 10,
                'communes_count' => 100,
                'status' => 'Active',
                'icon' => 'Landmark',
                'description' => 'Often referred to as the cradle of Khmer civilization, home to Funan-era archaeological sites like Phnom Da and Ta Mok\'s house.',
                'rating' => 4.55,
            ],
            [
                'name' => 'Tboung Khmum',
                'type' => 'Province',
                'population' => '775,740',
                'area' => '4,928 km²',
                'districts_count' => 7,
                'communes_count' => 64,
                'status' => 'Active',
                'icon' => 'Trees',
                'description' => 'Cambodia\'s newest province created in 2014, known for vast rubber plantations, pepper farms, and vibrant agricultural trade.',
                'rating' => 4.40,
            ],
        ];

        foreach ($provinces as $province) {
            Province::updateOrCreate(
                ['name' => $province['name']],
                $province
            );
        }
    }
}
