<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\UserAchievement;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds for all 5 RBAC roles and users.
     */
    public function run(): void
    {
        $password = Hash::make('password123');

        $users = [
            // ==================================================================
            // 1. SUPER ADMINS (2)
            // ==================================================================
            [
                'email' => 'admin@tourism.gov.kh',
                'name' => 'Ton Bunheng',
                'phone' => '+855 12 345 678',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_SUPER_ADMIN,
                'status' => 'Active',
                'location' => 'Phnom Penh',
                'verified' => true,
                'two_factor_auth' => true,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'Lead Administrator & Technical Architect for the AngkorVerses Tourism Information System.',
                'last_active_at' => now(),
            ],
            [
                'email' => 'sovannara.admin@tourism.gov.kh',
                'name' => 'Sovannara Rath',
                'phone' => '+855 11 888 234',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_SUPER_ADMIN,
                'status' => 'Active',
                'location' => 'Phnom Penh',
                'verified' => true,
                'two_factor_auth' => true,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'Senior Director of Digital Tourism Infrastructure, National Tourism Board of Cambodia.',
                'last_active_at' => now()->subMinutes(15),
            ],

            // ==================================================================
            // 2. ADMINS (3)
            // ==================================================================
            [
                'email' => 'staff.admin@tourism.gov.kh',
                'name' => 'Kosal Visal',
                'phone' => '+855 23 888 123',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_ADMIN,
                'status' => 'Active',
                'location' => 'Phnom Penh',
                'verified' => true,
                'two_factor_auth' => true,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'National tourism business verification and regional operator compliance supervisor.',
                'last_active_at' => now()->subHours(1),
            ],
            [
                'email' => 'sopheap.moderator@tourism.gov.kh',
                'name' => 'Chan Sopheap',
                'phone' => '+855 12 777 444',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_ADMIN,
                'status' => 'Active',
                'location' => 'Siem Reap',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'Content moderation manager supervising public review integrity and tourist support tickets.',
                'last_active_at' => now()->subHours(3),
            ],
            [
                'email' => 'vutha.support@tourism.gov.kh',
                'name' => 'Vutha Sambath',
                'phone' => '+855 23 999 555',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_ADMIN,
                'status' => 'Active',
                'location' => 'Phnom Penh',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Basic',
                'activity_level' => 'Medium',
                'bio' => 'Tourism analytics coordinator and platform helpdesk administrator.',
                'last_active_at' => now()->subDays(1),
            ],

            // ==================================================================
            // 3. GUIDE / CONTENT EDITORS (5)
            // ==================================================================
            [
                'email' => 'sopheaktra@tourism.gov.kh',
                'name' => 'Sophal Sopheaktra',
                'phone' => '+855 92 888 999',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_GUIDE_EDITOR,
                'status' => 'Active',
                'location' => 'Siem Reap',
                'verified' => true,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'Senior Khmer Culture & UNESCO World Heritage Certified Tour Guide with 14 years experience at Angkor Archaeological Park.',
                'last_active_at' => now()->subMinutes(30),
            ],
            [
                'email' => 'dara.guide@tourism.gov.kh',
                'name' => 'Meng Dara',
                'phone' => '+855 17 654 321',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_GUIDE_EDITOR,
                'status' => 'Active',
                'location' => 'Phnom Penh',
                'verified' => true,
                'subscription' => 'Basic',
                'activity_level' => 'High',
                'bio' => 'Phnom Penh Royal Palace historian, architectural docent, and Mekong river culture researcher.',
                'last_active_at' => now()->subHours(2),
            ],
            [
                'email' => 'sreymom.battambang@tourism.gov.kh',
                'name' => 'Srey Mom Khem',
                'phone' => '+855 53 951 753',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_GUIDE_EDITOR,
                'status' => 'Active',
                'location' => 'Battambang',
                'verified' => true,
                'subscription' => 'Basic',
                'activity_level' => 'High',
                'bio' => 'Battambang provincial arts curator, colonial heritage walk leader, and Phare circus ambassador.',
                'last_active_at' => now()->subDays(2),
            ],
            [
                'email' => 'rathana.eco@tourism.gov.kh',
                'name' => 'Heng Rathana',
                'phone' => '+855 73 888 777',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_GUIDE_EDITOR,
                'status' => 'Active',
                'location' => 'Mondulkiri',
                'verified' => true,
                'subscription' => 'Premium',
                'activity_level' => 'Medium',
                'bio' => 'Indigenous Bunong eco-trail master and wildlife protection advocate in Mondulkiri and Ratanakiri.',
                'last_active_at' => now()->subHours(6),
            ],
            [
                'email' => 'samnang.coastal@tourism.gov.kh',
                'name' => 'Kolap Samnang',
                'phone' => '+855 34 777 222',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_GUIDE_EDITOR,
                'status' => 'Active',
                'location' => 'Preah Sihanouk',
                'verified' => true,
                'subscription' => 'Basic',
                'activity_level' => 'Medium',
                'bio' => 'PADI certified divemaster and marine ecology guide for Koh Rong Archipelago and Kep coastal reserves.',
                'last_active_at' => now()->subDays(3),
            ],

            // ==================================================================
            // 4. BUSINESS OWNERS (5)
            // ==================================================================
            [
                'email' => 'owner@angkor-restaurant.com',
                'name' => 'Sokha Chanthou',
                'phone' => '+855 63 963 888',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_BUSINESS_OWNER,
                'status' => 'Active',
                'location' => 'Siem Reap',
                'verified' => true,
                'two_factor_auth' => true,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'Proprietor of Angkor Heritage Dining, Buger Bistro, and Tonle Sap Luxury Cruises.',
                'last_active_at' => now()->subMinutes(45),
            ],
            [
                'email' => 'malis.keo@khamisdining.kh',
                'name' => 'Keo Malis',
                'phone' => '+855 23 444 888',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_BUSINESS_OWNER,
                'status' => 'Active',
                'location' => 'Phnom Penh',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'Master Chef and operator of premier Living Cambodian Cuisine restaurants across Phnom Penh and Siem Reap.',
                'last_active_at' => now()->subHours(4),
            ],
            [
                'email' => 'david.miller@shinta-eco.com',
                'name' => 'David Miller',
                'phone' => '+855 95 333 111',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_BUSINESS_OWNER,
                'status' => 'Active',
                'location' => 'Koh Kong',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'General Manager of Cardamom Wilderness Tented Camps and Rainforest Eco-Expeditions.',
                'last_active_at' => now()->subDays(1),
            ],
            [
                'email' => 'jp.laurent@boutiquekhmer.com',
                'name' => 'Jean-Pierre Laurent',
                'phone' => '+855 33 666 999',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_BUSINESS_OWNER,
                'status' => 'Active',
                'location' => 'Kampot',
                'verified' => true,
                'two_factor_auth' => true,
                'subscription' => 'Premium',
                'activity_level' => 'Medium',
                'bio' => 'Managing Director of Kampot Heritage Riverfront Lodges and Bokor Mountain Bungalows.',
                'last_active_at' => now()->subHours(12),
            ],
            [
                'email' => 'thida.bodia@wellness.kh',
                'name' => 'Chhay Thida',
                'phone' => '+855 63 777 555',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_BUSINESS_OWNER,
                'status' => 'Active',
                'location' => 'Siem Reap',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Basic',
                'activity_level' => 'Medium',
                'bio' => 'Founder of Bodia Spa Retreats and Botanical Apothecary workshops in Siem Reap and Phnom Penh.',
                'last_active_at' => now()->subDays(2),
            ],

            // ==================================================================
            // 5. REGULAR USERS / TOURISTS (11)
            // ==================================================================
            [
                'email' => 'vit.vong@example.com',
                'name' => 'VIT Vong',
                'phone' => '+1 555 123 4567',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Active',
                'location' => 'United States',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'Avid travel writer, heritage photographer, and temple explorer documenting Southeast Asian civilisations.',
                'last_active_at' => now()->subHours(1),
            ],
            [
                'email' => 'ou.sreylin@example.com',
                'name' => 'Ou Sreylin',
                'phone' => '+855 10 999 000',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Active',
                'location' => 'Battambang',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Basic',
                'activity_level' => 'High',
                'bio' => 'Local heritage preservationist, eco-tourism enthusiast, and Khmer classical dance patron.',
                'last_active_at' => now()->subMinutes(20),
            ],
            [
                'email' => 'liam.smith@example.com',
                'name' => 'Liam Smith',
                'phone' => '+61 412 345 678',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Active',
                'location' => 'Australia',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Free',
                'activity_level' => 'High',
                'bio' => 'Backpacker and diver exploring the southern islands and Cardamom national parks.',
                'last_active_at' => now()->subDays(1),
            ],
            [
                'email' => 'claire.dubois@example.com',
                'name' => 'Claire Dubois',
                'phone' => '+33 6 12 34 56 78',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Active',
                'location' => 'France',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Premium',
                'activity_level' => 'Medium',
                'bio' => 'Architectural historian researching French colonial facades and Angkor bas-reliefs.',
                'last_active_at' => now()->subHours(5),
            ],
            [
                'email' => 'kenji.takahashi@example.com',
                'name' => 'Kenji Takahashi',
                'phone' => '+81 90 1234 5678',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Active',
                'location' => 'Japan',
                'verified' => true,
                'two_factor_auth' => true,
                'subscription' => 'Premium',
                'activity_level' => 'High',
                'bio' => 'Professional photographer on a photographic mission to capture all 1,000+ faces of the Bayon and Banteay Chhmar.',
                'last_active_at' => now()->subHours(2),
            ],
            [
                'email' => 'elena.rostova@example.com',
                'name' => 'Elena Rostova',
                'phone' => '+49 151 23456789',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Active',
                'location' => 'Germany',
                'verified' => false,
                'two_factor_auth' => false,
                'subscription' => 'Free',
                'activity_level' => 'Medium',
                'bio' => 'Foodie and travel blogger searching for Cambodia\'s freshest Kampot pepper crab and fish amok.',
                'last_active_at' => now()->subDays(2),
            ],
            [
                'email' => 'chen.wei@example.com',
                'name' => 'Chen Wei',
                'phone' => '+65 9123 4567',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Active',
                'location' => 'Singapore',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Basic',
                'activity_level' => 'Low',
                'bio' => 'Weekend weekend-breaker taking short trips to explore Siem Reap and Phnom Penh.',
                'last_active_at' => now()->subDays(4),
            ],
            [
                'email' => 'minjun.park@example.com',
                'name' => 'Min-jun Park',
                'phone' => '+82 10 9876 5432',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Active',
                'location' => 'South Korea',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Basic',
                'activity_level' => 'High',
                'bio' => 'Drone videographer documenting the misty mountains of Bokor and pristine beaches of Koh Rong Sanloem.',
                'last_active_at' => now()->subHours(8),
            ],
            [
                'email' => 'cheat.sok@example.com',
                'name' => 'Sok Cheat',
                'phone' => '+855 12 111 222',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Active',
                'location' => 'Phnom Penh',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Basic',
                'activity_level' => 'Medium',
                'bio' => 'Urban cycling enthusiast uncovering hidden riverside cafes and old pagodas.',
                'last_active_at' => now()->subDays(1),
            ],
            [
                'email' => 'sarah.jenkins@example.com',
                'name' => 'Sarah Jenkins',
                'phone' => '+44 7700 900123',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Inactive',
                'location' => 'United Kingdom',
                'verified' => true,
                'two_factor_auth' => false,
                'subscription' => 'Free',
                'activity_level' => 'Low',
                'bio' => 'Wildlife conservationist previously volunteering at the Elephant Valley Project in Mondulkiri.',
                'last_active_at' => now()->subMonths(1),
            ],
            [
                'email' => 'marcus.becker@example.com',
                'name' => 'Marcus Becker',
                'phone' => '+41 79 123 45 67',
                'password_hash' => $password,
                'avatar' => null,
                'role' => User::ROLE_USER,
                'status' => 'Suspended',
                'location' => 'Switzerland',
                'verified' => false,
                'two_factor_auth' => false,
                'subscription' => 'Free',
                'activity_level' => 'Low',
                'bio' => 'Account under temporary administrative review for multiple rapid unverified booking submissions.',
                'last_active_at' => now()->subWeeks(2),
            ],
        ];

        foreach ($users as $data) {
            $user = User::updateOrCreate(
                ['email' => $data['email']],
                $data
            );

            // Seed user achievements for tourists
            if ($user->role === User::ROLE_USER && $user->status === 'Active') {
                UserAchievement::firstOrCreate(
                    ['user_id' => $user->id, 'achievement_name' => 'Heritage Explorer'],
                    [
                        'description' => 'Visited 5 UNESCO World Heritage sites across Cambodia.',
                        'icon' => 'Award',
                        'unlocked' => true,
                        'unlocked_at' => now()->subDays(rand(3, 30)),
                    ]
                );

                UserAchievement::firstOrCreate(
                    ['user_id' => $user->id, 'achievement_name' => 'Culture Enthusiast'],
                    [
                        'description' => 'Attended live traditional Khmer Apsara dance performance.',
                        'icon' => 'Sparkles',
                        'unlocked' => true,
                        'unlocked_at' => now()->subDays(rand(1, 15)),
                    ]
                );

                UserAchievement::firstOrCreate(
                    ['user_id' => $user->id, 'achievement_name' => 'Angkor Sunrise Chaser'],
                    [
                        'description' => 'Checked in at Angkor Wat reflection pond before dawn.',
                        'icon' => 'Sun',
                        'unlocked' => rand(0, 1) === 1,
                        'unlocked_at' => now()->subDays(rand(1, 10)),
                    ]
                );
            }
        }
    }
}
